name: Check
on:
  workflow_dispatch:
# pull_request:
#   branches: [main]
#   paths:
#     - 'src/**'
#     - 'package.json'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run check
        run: bun run check && bun run check-types
